### ISSUE TITLE
Scale Denominator - NZTM2000TileMatrixSet

### ISSUE THREAD

**Issue by xycarto** [linz/NZTM2000TileMatrixSet#49]
Maybe this isn't an issue, but moreso a query about the NZTM Standard for scales in the [NZTM2000TileMatrixSet](https://github.com/linz/NZTM2000TileMatrixSet/blob/master/raw/NZTM2000.json).

I have used the LINZ standard for years for the NZTM map tile schema here: https://www.linz.govt.nz/data/linz-data-service/guides-and-documentation/nztm2000-map-tile-service-schema, however, I cannot find an answer as to why the schema uses the specific scale denominators it uses. For example, standard online map scaling usually uses a factor of two for scaling to the next zoom level, but the LINZ standard uses a different method e.g at the 250 000 scale the next scale is 100 000.  If there was any documentation as to why this happens it would be greatly appreciated. Further, if there was an demonstration equation on how the scales were determined that would be ace!

Currently I am working with the following to determine the base scale:

```
(cos(latitude * pi/180) * 2 * pi * (NZTM Width in meters / scale factor) * screen dpi) / (256 * 2 level * 0.0254)
```

where;
latitude = -40.9
scale factor  = 1.32
NZTM Width in meters = Xmax-Xmin for the NZTM extent

And this can be used to find the base scale of 32 000 000, however, I cannot see how the scales are reduced to develop the schema.I suspect the schema scales have something to with the LINZ topo series maps (50k, 1 million, etc), but this only a hunch.  Maybe it goes much deeper than this and there is a mathematical reason why this occurs?

**Comment by xycarto** [comment]
Full method I am using to determine the base scale:

```
import math
from pyproj import Proj, transform

inProj = Proj(init='epsg:2193')
outProj = Proj(init='epsg:4326')
x1,y1 = 1743159.15,5469287.49
x2,y2 = transform(inProj,outProj,x1,y1)
print(y2)

# Flattening based on ellipsoid and derived from: 
# https://www.linz.govt.nz/data/geodetic-system/datums-projections-and-heights/geodetic-datums/reference-ellipsoids
flattening = 298.257
f = 1/flattening
e2 = (2-f)*f

deg = math.radians(40.75)
scale_factor = math.sqrt( 1 - e2 * math.sin(deg)**2) / math.cos(deg)

minx = 274000
maxx =  3327000
miny = 3087000
maxy = 7173000

base_width = abs(maxx - minx)
base_scale = round((math.cos(deg * math.radians(math.pi/180)) * (base_width / scale_factor) * 90.7) / ((256 * 2**0) * 0.0254))
print(base_scale)
```

**Comment by blacha** [comment]
For some reason I didnt get notified about this issue being created :( so appologies for the slow response.

The [NZTM2000TileMatrixSet](https://github.com/linz/NZTM2000TileMatrixSet/blob/master/raw/NZTM2000.json) tile set was created before my time at LINZ so I dont have the full origin information. I believe it was designed to align with the cartographic maps at the time needing 1:250k 1:50k etc.

This scaling causes a huge amount of issues for the math involved in tiled matrix sets (it completely breaks quadkeys), so we recently created NZTM2000Quad that moves the scale levels to be the same as the WebMercatorQuad

I would highly recommend not using the original NZTM2000 tile matrix set.

**Comment by xycarto** [comment]
Thank you for the response.  I talked to a few folks inside the organization and received a similar answer.  I can see where there would be an issue with the maths on the original tile matrix and the customization needed to match the scales. I think your response sufficiently answers the question.  Thanks again
